Repository blackcowmoo/moo-mark, pull requests merged in 2020-07, with the labels that each got.

#29 SecurityConfig 프로파일로 환경에 따라 분리
  backend/auth/build.gradle
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/config/CustomOAuth2UserService.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/config/DevelopmentSecurityConfig.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/config/SecurityConfig.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/controller/UserController.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/service/NormalUserServiceImpl.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/service/OAuhUserServiceImpl.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/service/UserService.java
  backend/auth/src/main/java/com/blackcowmoo/moomark/auth/util/EnvironmentUtil.java
  backend/auth/src/main/resources-env/development/application.yml
  backend/auth/src/main/resources-env/production/application.yml
  backend/auth/src/main/resources/application-core.yml
  backend/auth/src/main/resources/application.yml
Labels: enhancement

#42 Add stomp plugin of rabbitmq
  docker-compose.yaml
  helm/templates/backend-rabbitmq.yaml
Labels: enhancement

#41 Remove unused script
  Jenkinsfile
Labels: bug

#40 Check docker files with github actions
  .github/workflows/docker-build.yaml
  .github/workflows/docker-lint.yaml
Labels: enhancement

#46 Upgrade packages for security (nodejs)
  frontend/package.json
  frontend/yarn.lock
  gateway/package.json
  gateway/yarn.lock
  package.json
  yarn.lock
Labels: bug

#44 Add rabbitmq management
  Jenkinsfile
  docker-compose.yaml
  helm/templates/backend-rabbitmq.yaml
  helm/values.yaml
Labels: enhancement

#51 Update packages for security (nodejs)
  frontend/yarn.lock
  gateway/yarn.lock
  yarn.lock
Labels: dependencies

#37 Setup gateway with apollo graphql
  .eslintrc
  Jenkinsfile
  docker-compose.yaml
  gateway/package.json
  gateway/src/core/app.ts
  gateway/src/core/config.ts
  gateway/src/core/graphql.ts
  gateway/src/graphql/index.ts
  gateway/src/graphql/mutation.ts
  gateway/src/graphql/query.ts
  gateway/src/index.ts
  gateway/src/test/graphql.test.ts
  gateway/src/test/utils/app.ts
  gateway/tsconfig.json
  gateway/yarn.lock
  helm/templates/gateway.yaml
Labels: enhancement

#45 Add redis-commander in test (PR)
  Jenkinsfile
  helm/templates/backend-redis.yaml
  helm/values.yaml
Labels: enhancement
